#!/usr/bin/env python3
"""Validate theme data and generate shell and zero-parse Rust catalog views."""
import argparse
import json
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parent.parent


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    catalog = json.loads((ROOT / "share/themes/catalog.json").read_text())
    outputs = {}
    rust = ["// Generated by scripts/generate-themes.py; edit share/themes/catalog.json.",
            "fn theme_value(theme: &str, key: &str) -> Option<&'static str> {", "    match theme {"]
    for name, values in catalog.items():
        result = subprocess.run(["jq", "-e", "-L", str(ROOT / "share/themes"),
                                 'include "validate"; valid_theme'],
                                input=json.dumps(values), text=True, capture_output=True)
        if result.returncode:
            sys.exit("Invalid theme: " + name)
        env = ["# Generated from catalog.json. Do not edit."]
        rust += [f"        {json.dumps(name)} => match key {{"]
        for key, value in values.items():
            # Values pass the constrained palette/glyph schema before code generation.
            escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$").replace("`", "\\`")
            env.append(': "${' + key + ':=' + escaped + '}"')
            rust.append(f"            {json.dumps(key)} => Some({json.dumps(value, ensure_ascii=False)}),")
        rust += ["            _ => None,", "        },"]
        outputs["share/themes/" + name + ".env"] = "\n".join(env) + "\n"
    rust += ["        _ => None,", "    }", "}", "fn known_theme(theme: &str) -> bool {",
             "    matches!(theme, " + " | ".join(json.dumps(name) for name in catalog) + ")", "}"]
    outputs["crates/showy-quota-zellij-core/src/themes_generated.rs"] = "\n".join(rust) + "\n"
    failures = []
    for filename, text in outputs.items():
        path = ROOT / filename
        if args.check:
            if not path.exists() or path.read_text() != text:
                failures.append(filename)
        else:
            path.write_text(text)
    if failures:
        sys.exit("Generated themes differ: " + ", ".join(failures))


if __name__ == "__main__":
    main()
