#!/usr/bin/env python3
"""Generate the runtime defaults, parsers, examples and reference from one contract."""
import argparse
import json
from pathlib import Path
import shlex
import sys

ROOT = Path(__file__).resolve().parent.parent


def rust_string(value):
    return json.dumps(value, ensure_ascii=False)


def rust_default(row):
    spec = row["rust"]
    value, kind = spec["default"], spec["type"]
    if spec.get("source") == "providers":
        return "crate::providers::default_order()"
    if value is None:
        return "None"
    if kind == "String":
        return rust_string(value) + ".into()"
    if kind == "bool":
        return str(value).lower()
    if kind == "Vec<String>":
        return "vec![" + ", ".join(rust_string(v) + ".into()" for v in value) + "]"
    if kind == "Vec<(String, String)>":
        return "vec![" + ", ".join("(" + rust_string(value[i]) + ".into(), " + rust_string(value[i + 1]) + ".into())" for i in range(0, len(value), 2)) + "]"
    if "BTreeMap" in kind:
        return "BTreeMap::new()"
    return str(value)


def generate(rows):
    defaults = ["// Generated by scripts/generate-config.py; edit share/config-manifest.json.",
                "impl Default for RenderConfig {", "    fn default() -> Self {", "        Self {"]
    parser = ["impl RenderConfig {", "    fn apply_manifest(&mut self, get: &dyn Fn(&str) -> Option<String>) {"]
    aliases = ["fn kdl_aliases(name: &str) -> &'static [&'static str] {", "    match name {"]
    shell = ["#!/usr/bin/env bash", "# Generated by scripts/generate-config.py; do not edit."]
    example = ["# Generated from share/config-manifest.json. Edit config.env, not this file.",
               "# config.env is trusted shell code. Theme manifests are JSON data.", ""]
    reference = ["# Configuration reference", "", "Generated from `share/config-manifest.json`.", "",
                 "| Environment key | KDL key | Type | Default | Scope | Description |",
                 "|---|---|---|---|---|---|"]
    for row in rows:
        key = row["key"]
        example += ["# " + row["description"], "# " + key + "=" + shlex.quote(str(row["default"] if row["default"] is not None else "")), ""]
        cells = [key, row.get("kdl") or "—", row["type"], str(row["default"]), ", ".join(row["scope"]), row["description"]]
        reference.append("| " + " | ".join(c.replace("|", "\\|").replace("\n", " ") for c in cells) + " |")
        if "shell" in row:
            spec = row["shell"]
            if key == "SHOWY_QUOTA_SKETCHYBAR_BAR_WIDTH":
                shell += ["showy_quota_uint_config SHOWY_QUOTA_PNG_BAR_W 80 4096",
                          "showy_quota_uint_config SHOWY_QUOTA_PNG_BAR_H 18 4096"]
            shell.append(': "${' + key + spec["operator"] + spec["default"] + '}"')
        if "rust" not in row:
            continue
        spec = row["rust"]
        field, kind = spec["field"], spec["type"]
        defaults.append(f"            {field}: {rust_default(row)},")
        if field == "theme":
            continue
        current = "self." + field
        key_literal = rust_string(key)
        if field in ("palette_countdown_warn", "palette_stale"):
            fallback = "palette_primary_bad" if field == "palette_countdown_warn" else "palette_primary_unknown"
            code = f"{current} = get({key_literal}).unwrap_or_else(|| self.{fallback}.clone());"
        elif row["type"] == "timezone":
            code = f"{current} = get_timezone_offset_minutes(&get, {key_literal}, {current});"
        elif kind in ("bool", "i32", "i64", "usize"):
            getter = {"bool": "get_bool", "i32": "get_i32", "i64": "get_i64", "usize": "get_usize"}[kind]
            code = f"{current} = {getter}(&get, {key_literal}, {current});"
        elif kind == "Option<usize>":
            code = f"{current} = get({key_literal}).and_then(|value| value.parse().ok()).or({current});"
        elif kind == "Vec<String>":
            code = f"{current} = get_csv(&get, {key_literal}, &{current});"
        elif kind == "Vec<(String, String)>":
            code = f"{current} = get_provider_modes(&get, {key_literal}, &{current});"
        elif "ThresholdOverride" in kind:
            code = f"if let Some(value) = get({key_literal}) {{ {current} = parse_thresholds(&value); }}"
        elif kind == "Option<String>":
            code = f"assign_option(&get, {key_literal}, &mut {current});"
        elif field in ("freshness", "vertical_sort"):
            allowed = " | ".join(rust_string(v) for v in row["allowed"])
            code = f"if let Some(value) = get({key_literal}) {{ let value = value.trim().to_ascii_lowercase(); if matches!(value.as_str(), {allowed}) {{ {current} = value; }} }}"
        else:
            assign = "assign_glyph" if row["type"] == "glyph" else "assign_string"
            code = f"{assign}(&get, {key_literal}, &mut {current});"
        parser.append("        " + code)
    for row in rows:
        if row.get("kdl") and "rust" in row:
            aliases.append(f'        {rust_string(row["key"])} => &[{rust_string(row["kdl"])}],')
    defaults += ["            theme_error: None,", "        }", "    }", "}"]
    parser += ["    }", "}"]
    aliases += ["        _ => &[],", "    }", "}"]
    return {"crates/showy-quota-zellij-core/src/config_generated.rs": "\n".join(defaults + parser + aliases) + "\n",
            "lib/config-defaults.sh": "\n".join(shell) + "\n",
            "share/config.env.example": "\n".join(example) + "\n",
            "docs/configuration.md": "\n".join(reference) + "\n"}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rows = json.loads((ROOT / "share/config-manifest.json").read_text())["settings"]
    failures = []
    for filename, text in generate(rows).items():
        path = ROOT / filename
        if args.check:
            if not path.exists() or path.read_text() != text:
                failures.append(filename)
        else:
            path.write_text(text)
    if failures:
        sys.exit("Generated configuration differs: " + ", ".join(failures))


if __name__ == "__main__":
    main()
