// Generated by scripts/generate-config.py; edit share/config-manifest.json.
impl Default for RenderConfig {
    fn default() -> Self {
        Self {
            providers: vec![],
            providers_exclude: vec![],
            provider_order: crate::providers::default_order(),
            include_status: true,
            palette_primary_good: "25be6a".into(),
            palette_primary_warn: "f0af00".into(),
            palette_primary_bad: "ee5396".into(),
            palette_primary_unknown: "6c7086".into(),
            palette_dim_scale: "0.55".into(),
            dim_window_minutes: 10080,
            palette_bg: "161616".into(),
            palette_surface: "2a2a2a".into(),
            palette_track: "3a3a4a".into(),
            palette_icon_text: "f2f4f8".into(),
            palette_countdown: "7b8496".into(),
            palette_countdown_warn: "ee5396".into(),
            palette_stale: "6c7086".into(),
            palette_elapsed: "be95ff".into(),
            palette_elapsed_long: "3ddbd9".into(),
            stale_glyph: "⚠".into(),
            degraded_cli_glyph: "⚠cli".into(),
            good_min_remaining: 40,
            warn_min_remaining: 15,
            time_warn_minutes: 30,
            zellij_bar_width: 12,
            terminal_bar_mode: "auto".into(),
            provider_modes: vec![("gemini".into(), "mono3".into())],
            mono_color_mode: "lowest".into(),
            mono_markers: vec!["primary".into()],
            provider_thresholds: BTreeMap::new(),
            window_thresholds: BTreeMap::new(),
            windows: vec!["primary".into(), "secondary".into(), "tertiary".into()],
            window_mode: "all".into(),
            compact_provider_count: 0,
            width_budget: 0,
            compact_order: "ordered".into(),
            freshness: "off".into(),
            severity_glyphs: false,
            palette_dim_good: None,
            palette_dim_warn: None,
            palette_dim_bad: None,
            palette_dim_unknown: None,
            error_glyph: "⚠".into(),
            reset_description_timezone_offset_minutes: None,
            theme: "default".into(),
            tmux_bar_width: None,
            vertical_bar_width: 16,
            vertical_sort: "provider".into(),
            vertical_reset_clock: true,
            cap_left: "".into(),
            cap_right: "".into(),
            theme_error: None,
        }
    }
}
impl RenderConfig {
    fn apply_manifest(&mut self, get: &dyn Fn(&str) -> Option<String>) {
        self.providers = get_csv(&get, "SHOWY_QUOTA_PROVIDERS", &self.providers);
        self.providers_exclude = get_csv(&get, "SHOWY_QUOTA_PROVIDERS_EXCLUDE", &self.providers_exclude);
        self.provider_order = get_csv(&get, "SHOWY_QUOTA_PROVIDER_ORDER", &self.provider_order);
        self.include_status = get_bool(&get, "SHOWY_QUOTA_INCLUDE_STATUS", self.include_status);
        assign_string(&get, "SHOWY_QUOTA_PALETTE_PRIMARY_GOOD", &mut self.palette_primary_good);
        assign_string(&get, "SHOWY_QUOTA_PALETTE_PRIMARY_WARN", &mut self.palette_primary_warn);
        assign_string(&get, "SHOWY_QUOTA_PALETTE_PRIMARY_BAD", &mut self.palette_primary_bad);
        assign_string(&get, "SHOWY_QUOTA_PALETTE_PRIMARY_UNKNOWN", &mut self.palette_primary_unknown);
        assign_string(&get, "SHOWY_QUOTA_PALETTE_DIM_SCALE", &mut self.palette_dim_scale);
        self.dim_window_minutes = get_i64(&get, "SHOWY_QUOTA_DIM_WINDOW_MINUTES", self.dim_window_minutes);
        assign_string(&get, "SHOWY_QUOTA_PALETTE_BG", &mut self.palette_bg);
        assign_string(&get, "SHOWY_QUOTA_PALETTE_SURFACE", &mut self.palette_surface);
        assign_string(&get, "SHOWY_QUOTA_PALETTE_TRACK", &mut self.palette_track);
        assign_string(&get, "SHOWY_QUOTA_PALETTE_ICON_TEXT", &mut self.palette_icon_text);
        assign_string(&get, "SHOWY_QUOTA_PALETTE_COUNTDOWN", &mut self.palette_countdown);
        self.palette_countdown_warn = get("SHOWY_QUOTA_PALETTE_COUNTDOWN_WARN").unwrap_or_else(|| self.palette_primary_bad.clone());
        self.palette_stale = get("SHOWY_QUOTA_PALETTE_STALE").unwrap_or_else(|| self.palette_primary_unknown.clone());
        assign_string(&get, "SHOWY_QUOTA_PALETTE_ELAPSED", &mut self.palette_elapsed);
        assign_string(&get, "SHOWY_QUOTA_PALETTE_ELAPSED_LONG", &mut self.palette_elapsed_long);
        assign_glyph(&get, "SHOWY_QUOTA_STALE_GLYPH", &mut self.stale_glyph);
        assign_glyph(&get, "SHOWY_QUOTA_DEGRADED_CLI_GLYPH", &mut self.degraded_cli_glyph);
        self.good_min_remaining = get_i32(&get, "SHOWY_QUOTA_GOOD_MIN_REMAINING", self.good_min_remaining);
        self.warn_min_remaining = get_i32(&get, "SHOWY_QUOTA_WARN_MIN_REMAINING", self.warn_min_remaining);
        self.time_warn_minutes = get_i64(&get, "SHOWY_QUOTA_TIME_WARN_MINUTES", self.time_warn_minutes);
        self.zellij_bar_width = get_usize(&get, "SHOWY_QUOTA_ZELLIJ_BAR_WIDTH", self.zellij_bar_width);
        assign_string(&get, "SHOWY_QUOTA_TERMINAL_BAR_MODE", &mut self.terminal_bar_mode);
        self.provider_modes = get_provider_modes(&get, "SHOWY_QUOTA_PROVIDER_MODES", &self.provider_modes);
        assign_string(&get, "SHOWY_QUOTA_MONO_COLOR_MODE", &mut self.mono_color_mode);
        self.mono_markers = get_csv(&get, "SHOWY_QUOTA_MONO_MARKERS", &self.mono_markers);
        if let Some(value) = get("SHOWY_QUOTA_PROVIDER_THRESHOLDS") { self.provider_thresholds = parse_thresholds(&value); }
        if let Some(value) = get("SHOWY_QUOTA_WINDOW_THRESHOLDS") { self.window_thresholds = parse_thresholds(&value); }
        self.windows = get_csv(&get, "SHOWY_QUOTA_WINDOWS", &self.windows);
        assign_string(&get, "SHOWY_QUOTA_WINDOW_MODE", &mut self.window_mode);
        self.compact_provider_count = get_usize(&get, "SHOWY_QUOTA_COMPACT_PROVIDER_COUNT", self.compact_provider_count);
        self.width_budget = get_usize(&get, "SHOWY_QUOTA_WIDTH_BUDGET", self.width_budget);
        assign_string(&get, "SHOWY_QUOTA_COMPACT_ORDER", &mut self.compact_order);
        if let Some(value) = get("SHOWY_QUOTA_FRESHNESS") { let value = value.trim().to_ascii_lowercase(); if matches!(value.as_str(), "off" | "age" | "source" | "age+source") { self.freshness = value; } }
        self.severity_glyphs = get_bool(&get, "SHOWY_QUOTA_SEVERITY_GLYPHS", self.severity_glyphs);
        assign_option(&get, "SHOWY_QUOTA_PALETTE_DIM_GOOD", &mut self.palette_dim_good);
        assign_option(&get, "SHOWY_QUOTA_PALETTE_DIM_WARN", &mut self.palette_dim_warn);
        assign_option(&get, "SHOWY_QUOTA_PALETTE_DIM_BAD", &mut self.palette_dim_bad);
        assign_option(&get, "SHOWY_QUOTA_PALETTE_DIM_UNKNOWN", &mut self.palette_dim_unknown);
        assign_glyph(&get, "SHOWY_QUOTA_ERROR_GLYPH", &mut self.error_glyph);
        self.reset_description_timezone_offset_minutes = get_timezone_offset_minutes(&get, "SHOWY_QUOTA_RESET_DESCRIPTION_TIMEZONE_OFFSET", self.reset_description_timezone_offset_minutes);
        self.tmux_bar_width = get("SHOWY_QUOTA_TMUX_BAR_WIDTH").and_then(|value| value.parse().ok()).or(self.tmux_bar_width);
        self.vertical_bar_width = get_usize(&get, "SHOWY_QUOTA_VERTICAL_BAR_WIDTH", self.vertical_bar_width);
        if let Some(value) = get("SHOWY_QUOTA_VERTICAL_SORT") { let value = value.trim().to_ascii_lowercase(); if matches!(value.as_str(), "provider" | "urgency") { self.vertical_sort = value; } }
        self.vertical_reset_clock = get_bool(&get, "SHOWY_QUOTA_VERTICAL_RESET_CLOCK", self.vertical_reset_clock);
        assign_glyph(&get, "SHOWY_QUOTA_CAP_LEFT", &mut self.cap_left);
        assign_glyph(&get, "SHOWY_QUOTA_CAP_RIGHT", &mut self.cap_right);
    }
}
fn kdl_aliases(name: &str) -> &'static [&'static str] {
    match name {
        "SHOWY_QUOTA_PROVIDERS" => &["providers"],
        "SHOWY_QUOTA_PROVIDERS_EXCLUDE" => &["providers_exclude"],
        "SHOWY_QUOTA_PROVIDER_ORDER" => &["provider_order"],
        "SHOWY_QUOTA_INCLUDE_STATUS" => &["include_status"],
        "SHOWY_QUOTA_PALETTE_PRIMARY_GOOD" => &["palette_primary_good"],
        "SHOWY_QUOTA_PALETTE_PRIMARY_WARN" => &["palette_primary_warn"],
        "SHOWY_QUOTA_PALETTE_PRIMARY_BAD" => &["palette_primary_bad"],
        "SHOWY_QUOTA_PALETTE_PRIMARY_UNKNOWN" => &["palette_primary_unknown"],
        "SHOWY_QUOTA_PALETTE_DIM_SCALE" => &["palette_dim_scale"],
        "SHOWY_QUOTA_DIM_WINDOW_MINUTES" => &["dim_window_minutes"],
        "SHOWY_QUOTA_PALETTE_BG" => &["palette_bg"],
        "SHOWY_QUOTA_PALETTE_SURFACE" => &["palette_surface"],
        "SHOWY_QUOTA_PALETTE_TRACK" => &["palette_track"],
        "SHOWY_QUOTA_PALETTE_ICON_TEXT" => &["palette_icon_text"],
        "SHOWY_QUOTA_PALETTE_COUNTDOWN" => &["palette_countdown"],
        "SHOWY_QUOTA_PALETTE_COUNTDOWN_WARN" => &["palette_countdown_warn"],
        "SHOWY_QUOTA_PALETTE_STALE" => &["palette_stale"],
        "SHOWY_QUOTA_PALETTE_ELAPSED" => &["palette_elapsed"],
        "SHOWY_QUOTA_PALETTE_ELAPSED_LONG" => &["palette_elapsed_long"],
        "SHOWY_QUOTA_STALE_GLYPH" => &["stale_glyph"],
        "SHOWY_QUOTA_DEGRADED_CLI_GLYPH" => &["degraded_cli_glyph"],
        "SHOWY_QUOTA_GOOD_MIN_REMAINING" => &["good_min_remaining"],
        "SHOWY_QUOTA_WARN_MIN_REMAINING" => &["warn_min_remaining"],
        "SHOWY_QUOTA_TIME_WARN_MINUTES" => &["time_warn_minutes"],
        "SHOWY_QUOTA_ZELLIJ_BAR_WIDTH" => &["bar_width"],
        "SHOWY_QUOTA_TERMINAL_BAR_MODE" => &["terminal_bar_mode"],
        "SHOWY_QUOTA_PROVIDER_MODES" => &["provider_modes"],
        "SHOWY_QUOTA_MONO_COLOR_MODE" => &["mono_color_mode"],
        "SHOWY_QUOTA_MONO_MARKERS" => &["mono_markers"],
        "SHOWY_QUOTA_PROVIDER_THRESHOLDS" => &["provider_thresholds"],
        "SHOWY_QUOTA_WINDOW_THRESHOLDS" => &["window_thresholds"],
        "SHOWY_QUOTA_WINDOWS" => &["windows"],
        "SHOWY_QUOTA_WINDOW_MODE" => &["window_mode"],
        "SHOWY_QUOTA_COMPACT_PROVIDER_COUNT" => &["compact_provider_count"],
        "SHOWY_QUOTA_WIDTH_BUDGET" => &["width_budget"],
        "SHOWY_QUOTA_COMPACT_ORDER" => &["compact_order"],
        "SHOWY_QUOTA_FRESHNESS" => &["freshness"],
        "SHOWY_QUOTA_SEVERITY_GLYPHS" => &["severity_glyphs"],
        "SHOWY_QUOTA_PALETTE_DIM_GOOD" => &["palette_dim_good"],
        "SHOWY_QUOTA_PALETTE_DIM_WARN" => &["palette_dim_warn"],
        "SHOWY_QUOTA_PALETTE_DIM_BAD" => &["palette_dim_bad"],
        "SHOWY_QUOTA_PALETTE_DIM_UNKNOWN" => &["palette_dim_unknown"],
        "SHOWY_QUOTA_ERROR_GLYPH" => &["error_glyph"],
        "SHOWY_QUOTA_RESET_DESCRIPTION_TIMEZONE_OFFSET" => &["reset_description_timezone_offset"],
        "SHOWY_QUOTA_THEME" => &["theme"],
        "SHOWY_QUOTA_TMUX_BAR_WIDTH" => &["tmux_bar_width"],
        "SHOWY_QUOTA_VERTICAL_BAR_WIDTH" => &["vertical_bar_width"],
        "SHOWY_QUOTA_VERTICAL_SORT" => &["vertical_sort"],
        "SHOWY_QUOTA_VERTICAL_RESET_CLOCK" => &["vertical_reset_clock"],
        "SHOWY_QUOTA_CAP_LEFT" => &["cap_left"],
        "SHOWY_QUOTA_CAP_RIGHT" => &["cap_right"],
        _ => &[],
    }
}
